[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/armon/go-radix"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  version = "0.5.10"

[[constraint]]
  branch = "master"
  name = "github.com/fredericlemoine/cobrashell"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"
