[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/armon/go-radix"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/fredericlemoine/cobrashell"
